[[headers]]
  for = "/pay"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
    Link = "</.well-known/payment-manifest.json>; rel=\"payment-method-manifest\""

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/app-manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
