[[redirects]]
  from = "/pay"
  to = "/pay.html"
  status = 200

[[headers]]
  for = "/pay"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/html"
    Link = "</.well-known/payment-manifest.json>; rel=\"payment-method-manifest\""

[[headers]]
  for = "/.well-known/payment-manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/pay-manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/app-manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
